"""Gold-facts authoring workflow.

Three subcommands:

    python gold_facts.py template --xlsx agent_benchmark_300_questions.xlsx
        Emits gold/gold_template.xlsx with one row per question and blank
        columns for you to fill in.

    python gold_facts.py merge --template gold/gold_template.xlsx
        Folds your filled-in template back into tasks/tasks_300.json.

    python gold_facts.py status --template gold/gold_template.xlsx
        Reports how much is filled in and what is still missing.

THIS SCRIPT NEVER WRITES GOLD FACTS FOR YOU. It creates blank rows.
The facts must be authored by you from real sources, because a fact
invented by a language model is not ground truth -- it is a guess that
would silently corrupt every quality score in the study.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))

GOLD_COLUMNS = [f"Gold_Fact_{i}" for i in range(1, 7)]

TEMPLATE_HEADERS = [
    "Question_ID", "Tier", "Industry / Field", "Topic", "Benchmark Prompt",
    *GOLD_COLUMNS,
    "Exact_Answer", "Required_Tools", "Source_Doc_IDs", "Answerable_From_Corpus",
    "Human_Verified", "Author_Notes",
]

INSTRUCTIONS = [
    ("HOW TO FILL THIS IN", ""),
    ("Gold_Fact_1..6",
     "Short checkable claims a correct answer MUST contain. Write them as "
     "the exact words that should appear, e.g. '35 percent' or 'duck curve'. "
     "3-6 per question. These are matched case-insensitively as substrings, "
     "so keep them short and unambiguous."),
    ("Exact_Answer",
     "Only for questions with ONE unambiguous answer (a number, a name). "
     "Leave blank for open-ended questions. When present, this becomes the "
     "deterministic exact-match metric."),
    ("Required_Tools",
     "Comma-separated: calculator, search_corpus, lookup_document. Which "
     "tools a correct solution genuinely needs. Used to detect tasks that "
     "can be answered from model memory alone."),
    ("Source_Doc_IDs",
     "Comma-separated corpus document ids (D001, D002...) that contain the "
     "gold facts. Every gold fact must be findable in at least one listed "
     "document, or the task is unanswerable."),
    ("Answerable_From_Corpus",
     "YES once you have confirmed the corpus actually contains every gold "
     "fact. validate_benchmark.py checks this automatically."),
    ("Human_Verified",
     "YES once a human has read the prompt and confirmed it is answerable, "
     "correctly tiered, and unambiguous."),
    ("Author_Notes", "Anything a co-author or reviewer should know."),
    ("", ""),
    ("RULE", "Do not paste facts generated by a language model. Take them "
             "from a real source and record that source in Author_Notes."),
    ("PRIORITY", "If time is short, fill Tier 3 first, then Tier 2. Tier 1 "
                 "questions are often exact-answer and quickest."),
]


def _load_workbook(path: Path):
    try:
        import openpyxl
    except ImportError:
        print("Need openpyxl:  pip install openpyxl")
        raise SystemExit(1)
    return openpyxl.load_workbook(path)


def cmd_template(args: argparse.Namespace) -> int:
    """Emit a blank authoring template, one row per question."""
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill

    wb_in = _load_workbook(Path(args.xlsx))
    ws_in = wb_in["Benchmark_300"]
    hdr = [c.value for c in ws_in[1]]
    rows = [dict(zip(hdr, r)) for r in ws_in.iter_rows(min_row=2, values_only=True)]

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Gold_Facts"

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="333333")
    todo_fill = PatternFill("solid", fgColor="FFF2CC")

    ws.append(TEMPLATE_HEADERS)
    for cell in ws[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(vertical="center", wrap_text=True)

    for r in rows:
        ws.append([
            r["Question_ID"], r["Tier"], r["Industry / Field"], r["Topic"],
            r["Benchmark Prompt"],
            *[""] * len(GOLD_COLUMNS),
            "", "", "", "NO", "NO", "",
        ])

    first_gold = TEMPLATE_HEADERS.index(GOLD_COLUMNS[0]) + 1
    last_col = len(TEMPLATE_HEADERS)
    for row in ws.iter_rows(min_row=2, min_col=first_gold, max_col=last_col):
        for cell in row:
            cell.fill = todo_fill

    widths = {"A": 12, "B": 10, "C": 22, "D": 24, "E": 70}
    for col, w in widths.items():
        ws.column_dimensions[col].width = w
    for i in range(first_gold, last_col + 1):
        ws.column_dimensions[openpyxl.utils.get_column_letter(i)].width = 26
    ws.freeze_panes = "F2"

    ws2 = wb.create_sheet("Instructions")
    ws2.append(["Field", "What to write"])
    for c in ws2[1]:
        c.font = header_font
        c.fill = header_fill
    for k, v in INSTRUCTIONS:
        ws2.append([k, v])
    ws2.column_dimensions["A"].width = 26
    ws2.column_dimensions["B"].width = 100
    for row in ws2.iter_rows(min_row=2):
        row[1].alignment = Alignment(wrap_text=True, vertical="top")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    print(f"Wrote blank template with {len(rows)} rows -> {out}")
    print("Open it in Excel. Yellow cells need your input.")
    return 0


def _read_template(path: Path) -> List[Dict[str, Any]]:
    wb = _load_workbook(path)
    ws = wb["Gold_Facts"]
    hdr = [c.value for c in ws[1]]
    return [dict(zip(hdr, r)) for r in ws.iter_rows(min_row=2, values_only=True)]


def _clean(v: Any) -> str:
    return str(v).strip() if v is not None else ""


def _facts_of(row: Dict[str, Any]) -> List[str]:
    return [_clean(row.get(c)) for c in GOLD_COLUMNS if _clean(row.get(c))]


def cmd_status(args: argparse.Namespace) -> int:
    """Report authoring progress without changing anything."""
    rows = _read_template(Path(args.template))
    by_tier: Counter = Counter()
    done_tier: Counter = Counter()
    no_facts, no_tools, no_sources, unverified = [], [], [], []

    for r in rows:
        tier = _clean(r.get("Tier")) or "?"
        by_tier[tier] += 1
        facts = _facts_of(r)
        if facts:
            done_tier[tier] += 1
        else:
            no_facts.append(r.get("Question_ID"))
        if not _clean(r.get("Required_Tools")):
            no_tools.append(r.get("Question_ID"))
        if not _clean(r.get("Source_Doc_IDs")):
            no_sources.append(r.get("Question_ID"))
        if _clean(r.get("Human_Verified")).upper() != "YES":
            unverified.append(r.get("Question_ID"))

    print(f"Rows: {len(rows)}\n")
    print("Gold facts written, by tier:")
    for tier in sorted(by_tier):
        n, d = by_tier[tier], done_tier[tier]
        pct = 100 * d / n if n else 0
        bar = "#" * int(pct / 5) + "." * (20 - int(pct / 5))
        print(f"  {tier:<8} {d:>3}/{n:<3} [{bar}] {pct:5.1f}%")

    print(f"\nMissing gold facts:      {len(no_facts)}")
    print(f"Missing required tools:  {len(no_tools)}")
    print(f"Missing source doc ids:  {len(no_sources)}")
    print(f"Not human-verified:      {len(unverified)}")

    total_done = sum(done_tier.values())
    if total_done == len(rows):
        print("\nAll rows have gold facts. Next: python gold_facts.py merge ...")
    else:
        print(f"\n{len(rows) - total_done} rows still need gold facts.")
    return 0


def cmd_merge(args: argparse.Namespace) -> int:
    """Fold the filled template into tasks.json."""
    rows = _read_template(Path(args.template))
    tasks_path = Path(args.tasks)
    if not tasks_path.exists():
        print(f"Task file not found: {tasks_path}")
        return 1

    payload = json.loads(tasks_path.read_text(encoding="utf-8"))
    tasks = payload["tasks"]
    by_id = {t["task_id"]: t for t in tasks}

    merged = skipped = 0
    for r in rows:
        qid = r.get("Question_ID")
        if qid is None:
            continue
        key = f"Q{int(qid):03d}"
        task = by_id.get(key)
        if task is None:
            continue

        facts = _facts_of(r)
        exact = _clean(r.get("Exact_Answer"))
        if not facts and not exact:
            skipped += 1
            continue

        task["gold_facts"] = facts
        if exact:
            task["expected_answer"] = exact
            task["evaluation_type"] = "exact_match"
        else:
            task["evaluation_type"] = "rubric"

        tools = _clean(r.get("Required_Tools"))
        if tools:
            task["required_tools"] = [t.strip() for t in tools.split(",") if t.strip()]
        docs = _clean(r.get("Source_Doc_IDs"))
        if docs:
            task["_source_doc_ids"] = [d.strip() for d in docs.split(",") if d.strip()]
        task["human_verified"] = _clean(r.get("Human_Verified")).upper() == "YES"
        notes = _clean(r.get("Author_Notes"))
        if notes:
            task["_author_notes"] = notes
        merged += 1

    out = Path(args.out or args.tasks)
    out.write_text(json.dumps({"tasks": tasks}, indent=2, ensure_ascii=False),
                   encoding="utf-8")

    grounded = sum(1 for t in tasks if t.get("gold_facts") or t.get("expected_answer"))
    print(f"Merged gold data into {merged} tasks ({skipped} rows were still blank).")
    print(f"Wrote -> {out}")
    print(f"\nGrounded tasks: {grounded}/{len(tasks)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Gold-facts authoring workflow")
    sub = ap.add_subparsers(dest="cmd", required=True)

    t = sub.add_parser("template", help="create a blank authoring template")
    t.add_argument("--xlsx", required=True, help="the 300-question workbook")
    t.add_argument("--out", default="gold/gold_template.xlsx")
    t.set_defaults(func=cmd_template)

    s = sub.add_parser("status", help="report authoring progress")
    s.add_argument("--template", default="gold/gold_template.xlsx")
    s.set_defaults(func=cmd_status)

    m = sub.add_parser("merge", help="merge the filled template into tasks.json")
    m.add_argument("--template", default="gold/gold_template.xlsx")
    m.add_argument("--tasks", default="tasks/tasks_150.json")
    m.add_argument("--out")
    m.set_defaults(func=cmd_merge)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
